DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS schools CASCADE;

DROP TABLE IF EXISTS subjects CASCADE;

DROP TABLE IF EXISTS users_subjects CASCADE;

DROP TABLE IF EXISTS units CASCADE;

DROP TABLE IF EXISTS standards CASCADE;

DROP TABLE IF EXISTS standards_sets CASCADE;

DROP TABLE IF EXISTS questions_schools CASCADE;

DROP TABLE IF EXISTS questions_subjects CASCADE;

DROP TABLE IF EXISTS questions CASCADE;

CREATE TABLE schools (
    id serial PRIMARY KEY,
    name text NOT NULL,
    district text NOT NULL,
    state text NOT NULL,
    jurisdiction_code text
);

CREATE TABLE users (
    id serial PRIMARY KEY,
    email text NOT NULL,
    password text NOT NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    school_id integer NOT NULL REFERENCES schools ON DELETE CASCADE,
    admin boolean NOT NULL DEFAULT FALSE
);

CREATE TABLE standards_sets (
    id serial PRIMARY KEY,
    source text NOT NULL,
    subject text NOT NULL,
    grade text NOT NULL
);

CREATE TABLE standards (
    id serial PRIMARY KEY,
    code text NOT NULL,
    description text NOT NULL,
    set_id integer NOT NULL REFERENCES standards_sets ON DELETE CASCADE
);

CREATE TABLE subjects (
    id serial PRIMARY KEY,
    name text NOT NULL,
    grade text NOT NULL,
    school_id integer NOT NULL REFERENCES schools ON DELETE CASCADE,
    set_id integer NOT NULL REFERENCES standards_sets ON DELETE CASCADE
);

CREATE TABLE users_subjects (
    id serial PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users ON DELETE CASCADE,
    subject_id integer NOT NULL REFERENCES subjects ON DELETE CASCADE
);

CREATE TABLE units (
    id serial PRIMARY KEY,
    subject_id integer NOT NULL REFERENCES subjects ON DELETE CASCADE,
    number integer NOT NULL,
    title text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    review_date date NOT NULL,
    planning jsonb NOT NULL DEFAULT '{}'::jsonb,
    collaboration jsonb NOT NULL DEFAULT '{}'::jsonb,
    completed boolean NOT NULL DEFAULT FALSE
);

CREATE TABLE questions (
    id serial PRIMARY KEY,
    text text NOT NULL
);

CREATE TABLE questions_subjects (
    id serial PRIMARY KEY,
    question_id integer NOT NULL REFERENCES questions ON DELETE CASCADE,
    subject_id integer NOT NULL REFERENCES subjects ON DELETE CASCADE
);

CREATE TABLE questions_schools (
    id serial PRIMARY KEY,
    question_id integer NOT NULL REFERENCES questions ON DELETE CASCADE,
    school_id integer NOT NULL REFERENCES schools ON DELETE CASCADE
);

INSERT INTO schools (name, district, state, jurisdiction_code)
    VALUES ('Cielo Azul', 'Rio Rancho', 'New Mexico', 'C558A97651934F3989D0D0A41196060C');

INSERT INTO users (email, PASSWORD, first_name, last_name, school_id, admin)
    VALUES ('teacher1@school.edu', '$2b$13$Ro0NvAv9zqoxkYG8ubn2j.jyO5OiT2RWuLa9qCMdIrdx0l2LLce.K', 'Carl', 'Smith', 1, FALSE), ('teacher2@school.edu', '$2b$13$jZFZifRPendj.gxvJeyZOevNoZ.O.z2qclvl18gMVXLImEl/ZgRAm', 'Kate', 'Wilkinson', 1, FALSE), ('teacher3@school.edu', '$2b$13$wNW9ZdwKLDxCRfMBbMHyo.giaRZX5V/69n1i6Pm5CxEpcvgb7hrKG', 'Julia', 'Packer', 1, FALSE), ('coach@school.edu', '$2b$13$1W83Qev/Il1Vis.80gRCpePuHj5fzLMmO7Pcsjxsltz6znQqci0Pm', 'Austin', 'Larkman', 1, TRUE);

INSERT INTO standards_sets (source, subject, grade)
    VALUES ('Common Core', 'MATH', '5'), ('Common Core', 'ELA', '5'), ('NGSS', 'SCIENCE', '5'), ('Common Core', 'ELA', '3');

INSERT INTO subjects (name, grade, school_id, set_id)
    VALUES ('ELA', '5', 1, 2), ('MATH', '5', 1, 1), ('SCIENCE', '5', 1, 3), ('ELA', '3', 1, 4);

INSERT INTO users_subjects (user_id, subject_id)
    VALUES (1, 1), (2, 1), (1, 2), (2, 2), (1, 3), (2, 3), (3, 4), (4, 1), (4, 2), (4, 3), (4, 4);

INSERT INTO questions (text)
    VALUES ('What skills are the students excelling at?'), ('What skills are the students struggling with?'), ('What are our common instructional commitments?'), ('How will we extend based on mastery?'), ('How will we intervene for students who are below proficient?');

INSERT INTO questions_schools (question_id, school_id)
    VALUES (1,1), (2,1), (3,1), (4,1), (5,1);

INSERT INTO standards (code, description, set_id)
    VALUES ('CCSS.ELA-Literacy.L.3.6',
  'Acquire and use accurately grade-appropriate conversational, general academic, and domain-specific words and phrases, including those that signal spatial and temporal relationships (e.g., After dinner that night we went looking for them).',
  4),
('CCSS.ELA-Literacy.L.3.5c',
  'Distinguish shades of meaning among related words that describe states of mind or degrees of certainty (e.g., knew, believed, suspected, heard, wondered).',
  4),
('CCSS.ELA-Literacy.L.3.5b',
  'Identify real-life connections between words and their use (e.g., describe people who are friendly or helpful).',
  4),
('CCSS.ELA-Literacy.L.3.5a',
  'Distinguish the literal and nonliteral meanings of words and phrases in context (e.g., take steps).',
  4),
('CCSS.ELA-Literacy.L.3.5',
  'Demonstrate understanding of word relationships and nuances in word meanings.',
  4),
('CCSS.ELA-Literacy.L.3.4d',
  'Use glossaries or beginning dictionaries, both print and digital, to determine or clarify the precise meaning of key words and phrases.',
  4),
('CCSS.ELA-Literacy.L.3.4c',
  'Use a known root word as a clue to the meaning of an unknown word with the same root (e.g., company, companion).',
  4),
('CCSS.ELA-Literacy.L.3.4b',
  'Determine the meaning of the new word formed when a known affix is added to a known word (e.g., agreeable/disagreeable, comfortable/uncomfortable, care/careless, heat/preheat).',
  4),
('CCSS.ELA-Literacy.L.3.4a',
  'Use sentence-level context as a clue to the meaning of a word or phrase.',
  4),
('CCSS.ELA-Literacy.L.3.4',
  'Determine or clarify the meaning of unknown and multiple-meaning word and phrases based on grade 3 reading and content, choosing flexibly from a range of strategies.',
  4),
('CCSS.ELA-Literacy.L.3.3b',
  'Recognize and observe differences between the conventions of spoken and written standard English.',
  4),
('CCSS.ELA-Literacy.L.3.3a',
  'Choose words and phrases for effect.',
  4),
('CCSS.ELA-Literacy.L.3.3',
  'Use knowledge of language and its conventions when writing, speaking, reading, or listening.',
  4),
('CCSS.ELA-Literacy.L.3.2g',
  'Consult reference materials, including beginning dictionaries, as needed to check and correct spellings.',
  4),
('CCSS.ELA-Literacy.L.3.2f',
  'Use spelling patterns and generalizations (e.g., word families, position-based spellings, syllable patterns, ending rules, meaningful word parts) in writing words.',
  4),
('CCSS.ELA-Literacy.L.3.2e',
  'Use conventional spelling for high-frequency and other studied words and for adding suffixes to base words (e.g., sitting, smiled, cries, happiness).',
  4),
('CCSS.ELA-Literacy.L.3.2d',
  'Form and use possessives.',
  4),
('CCSS.ELA-Literacy.L.3.2c',
  'Use commas and quotation marks in dialogue.',
  4),
('CCSS.ELA-Literacy.L.3.2b',
  'Use commas in addresses.',
  4),
('CCSS.ELA-Literacy.L.3.2a',
  'Capitalize appropriate words in titles.',
  4),
('CCSS.ELA-Literacy.L.3.2',
  'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.',
  4),
('CCSS.ELA-Literacy.L.3.1i',
  'Produce simple, compound, and complex sentences.',
  4),
('CCSS.ELA-Literacy.L.3.1h',
  'Use coordinating and subordinating conjunctions.',
  4),
('CCSS.ELA-Literacy.L.3.1g',
  'Form and use comparative and superlative adjectives and adverbs, and choose between them depending on what is to be modified.',
  4),
('CCSS.ELA-Literacy.L.3.1f',
  'Ensure subject-verb and pronoun-antecedent agreement.',
  4),
('CCSS.ELA-Literacy.L.3.1e',
  'Form and use the simple (e.g., I walked; I walk; I will walk) verb tenses.',
  4),
('CCSS.ELA-Literacy.L.3.1d',
  'Form and use regular and irregular verbs.',
  4),
('CCSS.ELA-Literacy.L.3.1c',
  'Use abstract nouns (e.g., childhood).',
  4),
('CCSS.ELA-Literacy.L.3.1b',
  'Form and use regular and irregular plural nouns.',
  4),
('CCSS.ELA-Literacy.L.3.1a',
  'Explain the function of nouns, pronouns, verbs, adjectives, and adverbs in general and their functions in particular sentences.',
  4),
('CCSS.ELA-Literacy.L.3.1',
  'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.',
  4),
('CCSS.ELA-Literacy.CCRA.L.6',
  'Acquire and use accurately a range of general academic and domain-specific words and phrases sufficient for reading, writing, speaking, and listening at the college and career readiness level; demonstrate independence in gathering vocabulary knowledge when encountering an unknown term important to comprehension or expression.',
  4),
('CCSS.ELA-Literacy.CCRA.L.5',
  'Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.',
  4),
('CCSS.ELA-Literacy.CCRA.L.4',
  'Determine or clarify the meaning of unknown and multiple-meaning words and phrases by using context clues, analyzing meaningful word parts, and consulting general and specialized reference materials, as appropriate.',
  4),
('CCSS.ELA-Literacy.CCRA.L.3',
  'Apply knowledge of language to understand how language functions in different contexts, to make effective choices for meaning or style, and to comprehend more fully when reading or listening.',
  4),
('CCSS.ELA-Literacy.CCRA.L.2',
  'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.',
  4),
('CCSS.ELA-Literacy.CCRA.L.1',
  'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.',
  4),
('CCSS.ELA-Literacy.SL.3.6',
  'Speak in complete sentences when appropriate to task and situation in order to provide requested detail or clarification.',
  4),
('CCSS.ELA-Literacy.SL.3.5',
  'Create engaging audio recordings of stories or poems that demonstrate fluid reading at an understandable pace; add visual displays when appropriate to emphasize or enhance certain facts or details.',
  4),
('CCSS.ELA-Literacy.SL.3.4',
  'Report on a topic or text, tell a story, or recount an experience with appropriate facts and relevant, descriptive details, speaking clearly at an understandable pace.',
  4),
('CCSS.ELA-Literacy.SL.3.3',
  'Ask and answer questions about information from a speaker, offering appropriate elaboration and detail.',
  4),
('CCSS.ELA-Literacy.SL.3.2',
  'Determine the main ideas and supporting details of a text read aloud or information presented in diverse media and formats, including visually, quantitatively, and orally.',
  4),
('CCSS.ELA-Literacy.SL.3.1d',
  'Explain their own ideas and understanding in light of the discussion.',
  4),
('CCSS.ELA-Literacy.SL.3.1c',
  'Ask questions to check understanding of information presented, stay on topic, and link their comments to the remarks of others.',
  4),
('CCSS.ELA-Literacy.SL.3.1b',
  'Follow agreed-upon rules for discussions (e.g., gaining the floor in respectful ways, listening to others with care, speaking one at a time about the topics and texts under discussion).',
  4),
('CCSS.ELA-Literacy.SL.3.1a',
  'Come to discussions prepared, having read or studied required material; explicitly draw on that preparation and other information known about the topic to explore ideas under discussion.',
  4),
('CCSS.ELA-Literacy.SL.3.1',
  'Engage effectively in a range of collaborative discussions (one-on-one, in groups, and teacher-led) with diverse partners on grade 3 topics and texts, building on others'' ideas and expressing their own clearly.',
  4),
('CCSS.ELA-Literacy.CCRA.SL.6',
  'Adapt speech to a variety of contexts and communicative tasks, demonstrating command of formal English when indicated or appropriate.',
  4),
('CCSS.ELA-Literacy.CCRA.SL.5',
  'Make strategic use of digital media and visual displays of data to express information and enhance understanding of presentations.',
  4),
('CCSS.ELA-Literacy.CCRA.SL.4',
  'Present information, findings, and supporting evidence such that listeners can follow the line of reasoning and the organization, development, and style are appropriate to task, purpose, and audience.',
  4),
('CCSS.ELA-Literacy.CCRA.SL.3',
  'Evaluate a speaker''s point of view, reasoning, and use of evidence and rhetoric.',
  4),
('CCSS.ELA-Literacy.CCRA.SL.2',
  'Integrate and evaluate information presented in diverse media and formats, including visually, quantitatively, and orally.',
  4),
('CCSS.ELA-Literacy.CCRA.SL.1',
  'Prepare for and participate effectively in a range of conversations and collaborations with diverse partners, building on others'' ideas and expressing their own clearly and persuasively.',
  4),
('CCSS.ELA-Literacy.W.3.10',
  'Write routinely over extended time frames (time for research, reflection, and revision) and shorter time frames (a single sitting or a day or two) for a range of discipline-specific tasks, purposes, and audiences.',
  4),
('CCSS.ELA-Literacy.W.3.8',
  'Recall information from experiences or gather information from print and digital sources; take brief notes on sources and sort evidence into provided categories.',
  4),
('CCSS.ELA-Literacy.W.3.7',
  'Conduct short research projects that build knowledge about a topic.',
  4),
('CCSS.ELA-Literacy.W.3.6',
  'With guidance and support from adults, use technology to produce and publish writing (using keyboarding skills) as well as to interact and collaborate with others.',
  4),
('CCSS.ELA-Literacy.W.3.5',
  'With guidance and support from peers and adults, develop and strengthen writing as needed by planning, revising, and editing.',
  4),
('CCSS.ELA-Literacy.W.3.4',
  'With guidance and support from adults, produce writing in which the development and organization are appropriate to task and purpose.',
  4),
('CCSS.ELA-Literacy.W.3.3d',
  'Provide a sense of closure.',
  4),
('CCSS.ELA-Literacy.W.3.3c',
  'Use temporal words and phrases to signal event order.',
  4),
('CCSS.ELA-Literacy.W.3.3b',
  'Use dialogue and descriptions of actions, thoughts, and feelings to develop experiences and events or show the response of characters to situations.',
  4),
('CCSS.ELA-Literacy.W.3.3a',
  'Establish a situation and introduce a narrator and/or characters; organize an event sequence that unfolds naturally.',
  4),
('CCSS.ELA-Literacy.W.3.3',
  'Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences.',
  4),
('CCSS.ELA-Literacy.W.3.2d',
  'Provide a concluding statement or section.',
  4),
('CCSS.ELA-Literacy.W.3.2c',
  'Use linking words and phrases (e.g., also, another, and, more, but) to connect ideas within categories of information.',
  4),
('CCSS.ELA-Literacy.W.3.2b',
  'Develop the topic with facts, definitions, and details.',
  4),
('CCSS.ELA-Literacy.W.3.2a',
  'Introduce a topic and group related information together; include illustrations when useful to aiding comprehension.',
  4),
('CCSS.ELA-Literacy.W.3.2',
  'Write informative/explanatory texts to examine a topic and convey ideas and information clearly.',
  4),
('CCSS.ELA-Literacy.W.3.1d',
  'Provide a concluding statement or section.',
  4),
('CCSS.ELA-Literacy.W.3.1c',
  'Use linking words and phrases (e.g., because, therefore, since, for example) to connect opinion and reasons.',
  4),
('CCSS.ELA-Literacy.W.3.1b',
  'Provide reasons that support the opinion.',
  4),
('CCSS.ELA-Literacy.W.3.1a',
  'Introduce the topic or text they are writing about, state an opinion, and create an organizational structure that lists reasons.',
  4),
('CCSS.ELA-Literacy.W.3.1',
  'Write opinion pieces on topics or texts, supporting a point of view with reasons.',
  4),
('CCSS.ELA-Literacy.CCRA.W.10',
  'Write routinely over extended time frames (time for research, reflection, and revision) and shorter time frames (a single sitting or a day or two) for a range of tasks, purposes, and audiences.',
  4),
('CCSS.ELA-Literacy.CCRA.W.9',
  'Draw evidence from literary or informational texts to support analysis, reflection, and research.',
  4),
('CCSS.ELA-Literacy.CCRA.W.8',
  'Gather relevant information from multiple print and digital sources, assess the credibility and accuracy of each source, and integrate the information while avoiding plagiarism.',
  4),
('CCSS.ELA-Literacy.CCRA.W.7',
  'Conduct short as well as more sustained research projects based on focused questions, demonstrating understanding of the subject under investigation.',
  4),
('CCSS.ELA-Literacy.CCRA.W.6',
  'Use technology, including the Internet, to produce and publish writing and to interact and collaborate with others.',
  4),
('CCSS.ELA-Literacy.CCRA.W.5',
  'Develop and strengthen writing as needed by planning, revising, editing, rewriting, or trying a new approach.',
  4),
('CCSS.ELA-Literacy.CCRA.W.4',
  'Produce clear and coherent writing in which the development, organization, and style are appropriate to task, purpose, and audience.',
  4),
('CCSS.ELA-Literacy.CCRA.W.3',
  'Write narratives to develop real or imagined experiences or events using effective technique, well-chosen details, and well-structured event sequences.',
  4),
('CCSS.ELA-Literacy.CCRA.W.2',
  'Write informative/explanatory texts to examine and convey complex ideas and information clearly and accurately through the effective selection, organization, and analysis of content.',
  4),
('CCSS.ELA-Literacy.CCRA.W.1',
  'Write arguments to support claims in an analysis of substantive topics or texts, using valid reasoning and relevant and sufficient evidence.',
  4),
('CCSS.ELA-Literacy.RF.3.4c',
  'Use context to confirm or self-correct word recognition and understanding, rereading as necessary.',
  4),
('CCSS.ELA-Literacy.RF.3.4b',
  'Read on-level prose and poetry orally with accuracy, appropriate rate, and expression on successive readings',
  4),
('CCSS.ELA-Literacy.RF.3.4a',
  'Read on-level text with purpose and understanding.',
  4),
('CCSS.ELA-Literacy.RF.3.4',
  'Read with sufficient accuracy and fluency to support comprehension.',
  4),
('CCSS.ELA-Literacy.RF.3.3d',
  'Read grade-appropriate irregularly spelled words.',
  4),
('CCSS.ELA-Literacy.RF.3.3c',
  'Decode multisyllable words.',
  4),
('CCSS.ELA-Literacy.RF.3.3b',
  'Decode words with common Latin suffixes.',
  4),
('CCSS.ELA-Literacy.RF.3.3a',
  'Identify and know the meaning of the most common prefixes and derivational suffixes.',
  4),
('CCSS.ELA-Literacy.RF.3.3',
  'Know and apply grade-level phonics and word analysis skills in decoding words.',
  4),
('CCSS.ELA-Literacy.RI.3.10',
  'By the end of the year, read and comprehend informational texts, including history/social studies, science, and technical texts, at the high end of the grades 2—3 text complexity band independently and proficiently.',
  4),
('CCSS.ELA-Literacy.RI.3.9',
  'Compare and contrast the most important points and key details presented in two texts on the same topic.',
  4),
('CCSS.ELA-Literacy.RI.3.8',
  'Describe the logical connection between particular sentences and paragraphs in a text (e.g., comparison, cause/effect, first/second/third in a sequence).',
  4),
('CCSS.ELA-Literacy.RI.3.7',
  'Use information gained from illustrations (e.g., maps, photographs) and the words in a text to demonstrate understanding of the text (e.g., where, when, why, and how key events occur).',
  4),
('CCSS.ELA-Literacy.RI.3.6',
  'Distinguish their own point of view from that of the author of a text.',
  4),
('CCSS.ELA-Literacy.RI.3.5',
  'Use text features and search tools (e.g., key words, sidebars, hyperlinks) to locate information relevant to a given topic efficiently.',
  4),
('CCSS.ELA-Literacy.RI.3.4',
  'Determine the meaning of general academic and domain-specific words and phrases in a text relevant to a grade 3 topic or subject area.',
  4),
('CCSS.ELA-Literacy.RI.3.3',
  'Describe the relationship between a series of historical events, scientific ideas or concepts, or steps in technical procedures in a text, using language that pertains to time, sequence, and cause/effect.',
  4),
('CCSS.ELA-Literacy.RI.3.2',
  'Determine the main idea of a text; recount the key details and explain how they support the main idea.',
  4),
('CCSS.ELA-Literacy.RI.3.1',
  'Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers.',
  4),
('CCSS.ELA-Literacy.RL.3.10',
  'By the end of the year, read and comprehend literature, including stories, dramas, and poetry, at the high end of the grades 2—3 text complexity band independently and proficiently.',
  4),
('CCSS.ELA-Literacy.RL.3.9',
  'Compare and contrast the themes, settings, and plots of stories written by the same author about the same or similar characters (e.g., in books from a series).',
  4),
('CCSS.ELA-Literacy.RL.3.7',
  'Explain how specific aspects of a text''s illustrations contribute to what is conveyed by the words in a story (e.g., create mood, emphasize aspects of a character or setting).',
  4),
('CCSS.ELA-Literacy.RL.3.6',
  'Distinguish their own point of view from that of the narrator or those of the characters.',
  4),
('CCSS.ELA-Literacy.RL.3.5',
  'Refer to parts of stories, dramas, and poems when writing or speaking about a text, using terms such as chapter, scene, and stanza; describe how each successive part builds on earlier sections.',
  4),
('CCSS.ELA-Literacy.RL.3.4',
  'Determine the meaning of words and phrases as they are used in a text, distinguishing literal from nonliteral language.',
  4),
('CCSS.ELA-Literacy.RL.3.3',
  'Describe characters in a story (e.g., their traits, motivations, or feelings) and explain how their actions contribute to the sequence of events.',
  4),
('CCSS.ELA-Literacy.RL.3.2',
  'Recount stories, including fables, folktales, and myths from diverse cultures; determine the central message, lesson, or moral and explain how it is conveyed through key details in the text.',
  4),
('CCSS.ELA-Literacy.RL.3.1',
  'Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers.',
  4),
('CCSS.ELA-Literacy.CCRA.R.10',
  'Read and comprehend complex literary and informational texts independently and proficiently.',
  4),
('CCSS.ELA-Literacy.CCRA.R.9',
  'Analyze how two or more texts address similar themes or topics in order to build knowledge or to compare the approaches the authors take.',
  4),
('CCSS.ELA-Literacy.CCRA.R.8',
  'Delineate and evaluate the argument and specific claims in a text, including the validity of the reasoning as well as the relevance and sufficiency of the evidence.',
  4),
('CCSS.ELA-Literacy.CCRA.R.7',
  'Integrate and evaluate content presented in diverse media and formats, including visually and quantitatively, as well as in words.',
  4),
('CCSS.ELA-Literacy.CCRA.R.6',
  'Assess how point of view or purpose shapes the content and style of a text.',
  4),
('CCSS.ELA-Literacy.CCRA.R.5',
  'Analyze the structure of texts, including how specific sentences, paragraphs, and larger portions of the text (e.g., a section, chapter, scene, or stanza) relate to each other and the whole.',
  4),
('CCSS.ELA-Literacy.CCRA.R.4',
  'Interpret words and phrases as they are used in a text, including determining technical, connotative, and figurative meanings, and analyze how specific word choices shape meaning or tone.',
  4),
('CCSS.ELA-Literacy.CCRA.R.3',
  'Analyze how and why individuals, events, and ideas develop and interact over the course of a text.',
  4),
('CCSS.ELA-Literacy.CCRA.R.2',
  'Determine central ideas or themes of a text and analyze their development; summarize the key supporting details and ideas.',
  4),
('CCSS.ELA-Literacy.CCRA.R.1',
  'Read closely to determine what the text says explicitly and to make logical inferences from it; cite specific textual evidence when writing or speaking to support conclusions drawn from the text.',
  4),
('CCSS.ELA-Literacy.L.5.6',
  'Acquire and use accurately grade-appropriate general academic and domain-specific words and phrases, including those that signal contrast, addition, and other logical relationships (e.g., however, although, nevertheless, similarly, moreover, in addition).',
  2),
('CCSS.ELA-Literacy.L.5.5c',
  'Use the relationship between particular words (e.g., synonyms, antonyms, homographs) to better understand each of the words.',
  2),
('CCSS.ELA-Literacy.L.5.5b',
  'Recognize and explain the meaning of common idioms, adages, and proverbs.',
  2),
('CCSS.ELA-Literacy.L.5.5a',
  'Interpret figurative language, including similes and metaphors, in context.',
  2),
('CCSS.ELA-Literacy.L.5.5',
  'Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.',
  2),
('CCSS.ELA-Literacy.L.5.4c',
  'Consult reference materials (e.g., dictionaries, glossaries, thesauruses), both print and digital, to find the pronunciation and determine or clarify the precise meaning of key words and phrases.',
  2),
('CCSS.ELA-Literacy.L.5.4b',
  'Use common, grade-appropriate Greek and Latin affixes and roots as clues to the meaning of a word (e.g., photograph, photosynthesis).',
  2),
('CCSS.ELA-Literacy.L.5.4a',
  'Use context (e.g., cause/effect relationships and comparisons in text) as a clue to the meaning of a word or phrase.',
  2),
('CCSS.ELA-Literacy.L.5.4',
  'Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 5 reading and content, choosing flexibly from a range of strategies.',
  2),
('CCSS.ELA-Literacy.L.5.3b',
  'Compare and contrast the varieties of English (e.g., dialects, registers) used in stories, dramas, or poems.',
  2),
('CCSS.ELA-Literacy.L.5.3a',
  'Expand, combine, and reduce sentences for meaning, reader/listener interest, and style.',
  2),
('CCSS.ELA-Literacy.L.5.3',
  'Use knowledge of language and its conventions when writing, speaking, reading, or listening.',
  2),
('CCSS.ELA-Literacy.L.5.2e',
  'Spell grade-appropriate words correctly, consulting references as needed.',
  2),
('CCSS.ELA-Literacy.L.5.2d',
  'Use underlining, quotation marks, or italics to indicate titles of works.',
  2),
('CCSS.ELA-Literacy.L.5.2c',
  'Use a comma to set off the words yes and no (e.g., Yes, thank you), to set off a tag question from the rest of the sentence (e.g., It''s true, isn''t it?), and to indicate direct address (e.g., Is that you, Steve?).',
  2),
('CCSS.ELA-Literacy.L.5.2b',
  'Use a comma to separate an introductory element from the rest of the sentence.',
  2),
('CCSS.ELA-Literacy.L.5.2a',
  'Use punctuation to separate items in a series.',
  2),
('CCSS.ELA-Literacy.L.5.2',
  'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.',
  2),
('CCSS.ELA-Literacy.L.5.1e',
  'Use correlative conjunctions (e.g., either/or, neither/nor).',
  2),
('CCSS.ELA-Literacy.L.5.1d',
  'Recognize and correct inappropriate shifts in verb tense.',
  2),
('CCSS.ELA-Literacy.L.5.1c',
  'Use verb tense to convey various times, sequences, states, and conditions.',
  2),
('CCSS.ELA-Literacy.L.5.1b',
  'Form and use the perfect (e.g., I had walked; I have walked; I will have walked) verb tenses.',
  2),
('CCSS.ELA-Literacy.L.5.1a',
  'Explain the function of conjunctions, prepositions, and interjections in general and their function in particular sentences.',
  2),
('CCSS.ELA-Literacy.L.5.1',
  'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.',
  2),
('CCSS.ELA-Literacy.CCRA.L.6',
  'Acquire and use accurately a range of general academic and domain-specific words and phrases sufficient for reading, writing, speaking, and listening at the college and career readiness level; demonstrate independence in gathering vocabulary knowledge when encountering an unknown term important to comprehension or expression.',
  2),
('CCSS.ELA-Literacy.CCRA.L.5',
  'Demonstrate understanding of figurative language, word relationships, and nuances in word meanings.',
  2),
('CCSS.ELA-Literacy.CCRA.L.4',
  'Determine or clarify the meaning of unknown and multiple-meaning words and phrases by using context clues, analyzing meaningful word parts, and consulting general and specialized reference materials, as appropriate.',
  2),
('CCSS.ELA-Literacy.CCRA.L.3',
  'Apply knowledge of language to understand how language functions in different contexts, to make effective choices for meaning or style, and to comprehend more fully when reading or listening.',
  2),
('CCSS.ELA-Literacy.CCRA.L.2',
  'Demonstrate command of the conventions of standard English capitalization, punctuation, and spelling when writing.',
  2),
('CCSS.ELA-Literacy.CCRA.L.1',
  'Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.',
  2),
('CCSS.ELA-Literacy.SL.5.6',
  'Adapt speech to a variety of contexts and tasks, using formal English when appropriate to task and situation.',
  2),
('CCSS.ELA-Literacy.SL.5.5',
  'Include multimedia components (e.g., graphics, sound) and visual displays in presentations when appropriate to enhance the development of main ideas or themes.',
  2),
('CCSS.ELA-Literacy.SL.5.4',
  'Report on a topic or text or present an opinion, sequencing ideas logically and using appropriate facts and relevant, descriptive details to support main ideas or themes; speak clearly at an understandable pace.',
  2),
('CCSS.ELA-Literacy.SL.5.3',
  'Summarize the points a speaker makes and explain how each claim is supported by reasons and evidence.',
  2),
('CCSS.ELA-Literacy.SL.5.2',
  'Summarize a written text read aloud or information presented in diverse media and formats, including visually, quantitatively, and orally.',
  2),
('CCSS.ELA-Literacy.SL.5.1d',
  'Review the key ideas expressed and draw conclusions in light of information and knowledge gained from the discussions.',
  2),
('CCSS.ELA-Literacy.SL.5.1c',
  'Pose and respond to specific questions by making comments that contribute to the discussion and elaborate on the remarks of others.',
  2),
('CCSS.ELA-Literacy.SL.5.1b',
  'Follow agreed-upon rules for discussions and carry out assigned roles.',
  2),
('CCSS.ELA-Literacy.SL.5.1a',
  'Come to discussions prepared, having read or studied required material; explicitly draw on that preparation and other information known about the topic to explore ideas under discussion.',
  2),
('CCSS.ELA-Literacy.SL.5.1',
  'Engage effectively in a range of collaborative discussions (one-on-one, in groups, and teacher-led) with diverse partners on grade 5 topics and texts, building on others'' ideas and expressing their own clearly.',
  2),
('CCSS.ELA-Literacy.CCRA.SL.6',
  'Adapt speech to a variety of contexts and communicative tasks, demonstrating command of formal English when indicated or appropriate.',
  2),
('CCSS.ELA-Literacy.CCRA.SL.5',
  'Make strategic use of digital media and visual displays of data to express information and enhance understanding of presentations.',
  2),
('CCSS.ELA-Literacy.CCRA.SL.4',
  'Present information, findings, and supporting evidence such that listeners can follow the line of reasoning and the organization, development, and style are appropriate to task, purpose, and audience.',
  2),
('CCSS.ELA-Literacy.CCRA.SL.3',
  'Evaluate a speaker''s point of view, reasoning, and use of evidence and rhetoric.',
  2),
('CCSS.ELA-Literacy.CCRA.SL.2',
  'Integrate and evaluate information presented in diverse media and formats, including visually, quantitatively, and orally.',
  2),
('CCSS.ELA-Literacy.CCRA.SL.1',
  'Prepare for and participate effectively in a range of conversations and collaborations with diverse partners, building on others'' ideas and expressing their own clearly and persuasively.',
  2),
('CCSS.ELA-Literacy.W.5.10',
  'Write routinely over extended time frames (time for research, reflection, and revision) and shorter time frames (a single sitting or a day or two) for a range of discipline-specific tasks, purposes, and audiences.',
  2),
('CCSS.ELA-Literacy.W.5.9b',
  'Apply grade 5 Reading standards to informational texts (e.g., "Explain how an author uses reasons and evidence to support particular points in a text, identifying which reasons and evidence support which point[s]").',
  2),
('CCSS.ELA-Literacy.W.5.9a',
  'Apply grade 5 Reading standards to literature (e.g., "Compare and contrast two or more characters, settings, or events in a story or a drama, drawing on specific details in the text [e.g., how characters interact]").',
  2),
('CCSS.ELA-Literacy.W.5.9',
  'Draw evidence from literary or informational texts to support analysis, reflection, and research.',
  2),
('CCSS.ELA-Literacy.W.5.8',
  'Recall relevant information from experiences or gather relevant information from print and digital sources; summarize or paraphrase information in notes and finished work, and provide a list of sources.',
  2),
('CCSS.ELA-Literacy.W.5.7',
  'Conduct short research projects that use several sources to build knowledge through investigation of different aspects of a topic.',
  2),
('CCSS.ELA-Literacy.W.5.6',
  'With some guidance and support from adults, use technology, including the Internet, to produce and publish writing as well as to interact and collaborate with others; demonstrate sufficient command of keyboarding skills to type a minimum of two pages in a single sitting.',
  2),
('CCSS.ELA-Literacy.W.5.5',
  'With guidance and support from peers and adults, develop and strengthen writing as needed by planning, revising, editing, rewriting, or trying a new approach.',
  2),
('CCSS.ELA-Literacy.W.5.4',
  'Produce clear and coherent writing in which the development and organization are appropriate to task, purpose, and audience.',
  2),
('CCSS.ELA-Literacy.W.5.3e',
  'Provide a conclusion that follows from the narrated experiences or events.',
  2),
('CCSS.ELA-Literacy.W.5.3d',
  'Use concrete words and phrases and sensory details to convey experiences and events precisely.',
  2),
('CCSS.ELA-Literacy.W.5.3c',
  'Use a variety of transitional words, phrases, and clauses to manage the sequence of events.',
  2),
('CCSS.ELA-Literacy.W.5.3b',
  'Use narrative techniques, such as dialogue, description, and pacing, to develop experiences and events or show the responses of characters to situations.',
  2),
('CCSS.ELA-Literacy.W.5.3a',
  'Orient the reader by establishing a situation and introducing a narrator and/or characters; organize an event sequence that unfolds naturally.',
  2),
('CCSS.ELA-Literacy.W.5.3',
  'Write narratives to develop real or imagined experiences or events using effective technique, descriptive details, and clear event sequences.',
  2),
('CCSS.ELA-Literacy.W.5.2e',
  'Provide a concluding statement or section related to the information or explanation presented',
  2),
('CCSS.ELA-Literacy.W.5.2d',
  'Use precise language and domain-specific vocabulary to inform about or explain the topic.',
  2),
('CCSS.ELA-Literacy.W.5.2c',
  'Link ideas within and across categories of information using words, phrases, and clauses (e.g., in contrast, especially).',
  2),
('CCSS.ELA-Literacy.W.5.2b',
  'Develop the topic with facts, definitions, concrete details, quotations, or other information and examples related to the topic.',
  2),
('CCSS.ELA-Literacy.W.5.2a',
  'Introduce a topic clearly, provide a general observation and focus, and group related information logically; include formatting (e.g., headings), illustrations, and multimedia when useful to aiding comprehension.',
  2),
('CCSS.ELA-Literacy.W.5.2',
  'Write informative/explanatory texts to examine a topic and convey ideas and information clearly.',
  2),
('CCSS.ELA-Literacy.W.5.1d',
  'Provide a concluding statement or section related to the opinion presented.',
  2),
('CCSS.ELA-Literacy.W.5.1c',
  'Link opinion and reasons using words, phrases, and clauses (e.g., consequently, specifically).',
  2),
('CCSS.ELA-Literacy.W.5.1b',
  'Provide logically ordered reasons that are supported by facts and details.',
  2),
('CCSS.ELA-Literacy.W.5.1a',
  'Introduce a topic or text clearly, state an opinion, and create an organizational structure in which ideas are logically grouped to support the writer''s purpose.',
  2),
('CCSS.ELA-Literacy.W.5.1',
  'Write opinion pieces on topics or texts, supporting a point of view with reasons and information',
  2),
('CCSS.ELA-Literacy.CCRA.W.10',
  'Write routinely over extended time frames (time for research, reflection, and revision) and shorter time frames (a single sitting or a day or two) for a range of tasks, purposes, and audiences.',
  2),
('CCSS.ELA-Literacy.CCRA.W.9',
  'Draw evidence from literary or informational texts to support analysis, reflection, and research.',
  2),
('CCSS.ELA-Literacy.CCRA.W.8',
  'Gather relevant information from multiple print and digital sources, assess the credibility and accuracy of each source, and integrate the information while avoiding plagiarism.',
  2),
('CCSS.ELA-Literacy.CCRA.W.7',
  'Conduct short as well as more sustained research projects based on focused questions, demonstrating understanding of the subject under investigation.',
  2),
('CCSS.ELA-Literacy.CCRA.W.6',
  'Use technology, including the Internet, to produce and publish writing and to interact and collaborate with others.',
  2),
('CCSS.ELA-Literacy.CCRA.W.5',
  'Develop and strengthen writing as needed by planning, revising, editing, rewriting, or trying a new approach.',
  2),
('CCSS.ELA-Literacy.CCRA.W.4',
  'Produce clear and coherent writing in which the development, organization, and style are appropriate to task, purpose, and audience.',
  2),
('CCSS.ELA-Literacy.CCRA.W.3',
  'Write narratives to develop real or imagined experiences or events using effective technique, well-chosen details, and well-structured event sequences.',
  2),
('CCSS.ELA-Literacy.CCRA.W.2',
  'Write informative/explanatory texts to examine and convey complex ideas and information clearly and accurately through the effective selection, organization, and analysis of content.',
  2),
('CCSS.ELA-Literacy.CCRA.W.1',
  'Write arguments to support claims in an analysis of substantive topics or texts, using valid reasoning and relevant and sufficient evidence.',
  2),
('CCSS.ELA-Literacy.RF.5.4c',
  'Use context to confirm or self-correct word recognition and understanding, rereading as necessary.',
  2),
('CCSS.ELA-Literacy.RF.5.4b',
  'Read on-level prose and poetry orally with accuracy, appropriate rate, and expression on successive readings',
  2),
('CCSS.ELA-Literacy.RF.5.4a',
  'Read on-level text with purpose and understanding.',
  2),
('CCSS.ELA-Literacy.RF.5.4',
  'Read with sufficient accuracy and fluency to support comprehension.',
  2),
('CCSS.ELA-Literacy.RF.5.3a',
  'Use combined knowledge of all letter-sound correspondences, syllabication patterns, and morphology (e.g., roots and affixes) to read accurately unfamiliar multisyllabic words in context and out of context.',
  2),
('CCSS.ELA-Literacy.RF.5.3',
  'Know and apply grade-level phonics and word analysis skills in decoding words.',
  2),
('CCSS.ELA-Literacy.RI.5.10',
  'By the end of the year, read and comprehend informational texts, including history/social studies, science, and technical texts, at the high end of the grades 4—5 text complexity band independently and proficiently.',
  2),
('CCSS.ELA-Literacy.RI.5.9',
  'Integrate information from several texts on the same topic in order to write or speak about the subject knowledgeably.',
  2),
('CCSS.ELA-Literacy.RI.5.8',
  'Explain how an author uses reasons and evidence to support particular points in a text, identifying which reasons and evidence support which point(s).',
  2),
('CCSS.ELA-Literacy.RI.5.7',
  'Draw on information from multiple print or digital sources, demonstrating the ability to locate an answer to a question quickly or to solve a problem efficiently.',
  2),
('CCSS.ELA-Literacy.RI.5.6',
  'Analyze multiple accounts of the same event or topic, noting important similarities and differences in the point of view they represent.',
  2),
('CCSS.ELA-Literacy.RI.5.5',
  'Compare and contrast the overall structure (e.g., chronology, comparison, cause/effect, problem/solution) of events, ideas, concepts, or information in two or more texts.',
  2),
('CCSS.ELA-Literacy.RI.5.4',
  'Determine the meaning of general academic and domain-specific words and phrases in a text relevant to a grade 5 topic or subject area.',
  2),
('CCSS.ELA-Literacy.RI.5.3',
  'Explain the relationships or interactions between two or more individuals, events, ideas, or concepts in a historical, scientific, or technical text based on specific information in the text.',
  2),
('CCSS.ELA-Literacy.RI.5.2',
  'Determine two or more main ideas of a text and explain how they are supported by key details; summarize the text.',
  2),
('CCSS.ELA-Literacy.RI.5.1',
  'Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.',
  2),
('CCSS.ELA-Literacy.RL.5.10',
  'By the end of the year, read and comprehend literature, including stories, dramas, and poetry, at the high end of the grades 4—5 text complexity band independently and proficiently.',
  2),
('CCSS.ELA-Literacy.RL.5.9',
  'Compare and contrast stories in the same genre (e.g., mysteries and adventure stories) on their approaches to similar themes and topics.',
  2),
('CCSS.ELA-Literacy.RL.5.7',
  'Analyze how visual and multimedia elements contribute to the meaning, tone, or beauty of a text (e.g., graphic novel, multimedia presentation of fiction, folktale, myth, poem).',
  2),
('CCSS.ELA-Literacy.RL.5.6',
  'Describe how a narrator''s or speaker''s point of view influences how events are described.',
  2),
('CCSS.ELA-Literacy.RL.5.5',
  'Explain how a series of chapters, scenes, or stanzas fits together to provide the overall structure of a particular story, drama, or poem.',
  2),
('CCSS.ELA-Literacy.RL.5.4',
  'Determine the meaning of words and phrases as they are used in a text, including figurative language such as metaphors and similes.',
  2),
('CCSS.ELA-Literacy.RL.5.3',
  'Compare and contrast two or more characters, settings, or events in a story or drama, drawing on specific details in the text (e.g., how characters interact).',
  2),
('CCSS.ELA-Literacy.RL.5.2',
  'Determine a theme of a story, drama, or poem from details in the text, including how characters in a story or drama respond to challenges or how the speaker in a poem reflects upon a topic; summarize the text.',
  2),
('CCSS.ELA-Literacy.RL.5.1',
  'Quote accurately from a text when explaining what the text says explicitly and when drawing inferences from the text.',
  2),
('CCSS.ELA-Literacy.CCRA.R.10',
  'Read and comprehend complex literary and informational texts independently and proficiently.',
  2),
('CCSS.ELA-Literacy.CCRA.R.9',
  'Analyze how two or more texts address similar themes or topics in order to build knowledge or to compare the approaches the authors take.',
  2),
('CCSS.ELA-Literacy.CCRA.R.8',
  'Delineate and evaluate the argument and specific claims in a text, including the validity of the reasoning as well as the relevance and sufficiency of the evidence.',
  2),
('CCSS.ELA-Literacy.CCRA.R.7',
  'Integrate and evaluate content presented in diverse media and formats, including visually and quantitatively, as well as in words.',
  2),
('CCSS.ELA-Literacy.CCRA.R.6',
  'Assess how point of view or purpose shapes the content and style of a text.',
  2),
('CCSS.ELA-Literacy.CCRA.R.5',
  'Analyze the structure of texts, including how specific sentences, paragraphs, and larger portions of the text (e.g., a section, chapter, scene, or stanza) relate to each other and the whole.',
  2),
('CCSS.ELA-Literacy.CCRA.R.4',
  'Interpret words and phrases as they are used in a text, including determining technical, connotative, and figurative meanings, and analyze how specific word choices shape meaning or tone.',
  2),
('CCSS.ELA-Literacy.CCRA.R.3',
  'Analyze how and why individuals, events, and ideas develop and interact over the course of a text.',
  2),
('CCSS.ELA-Literacy.CCRA.R.2',
  'Determine central ideas or themes of a text and analyze their development; summarize the key supporting details and ideas.',
  2),
('CCSS.ELA-Literacy.CCRA.R.1',
  'Read closely to determine what the text says explicitly and to make logical inferences from it; cite specific textual evidence when writing or speaking to support conclusions drawn from the text.',
  2),
('CCSS.Math.Content.5.NF.B.7c',
  'Solve real world problems involving division of unit fractions by non-zero whole numbers and division of whole numbers by unit fractions, e.g., by using visual fraction models and equations to represent the problem.',
  1),
('CCSS.Math.Content.5.NF.B.7b',
  'Interpret division of a whole number by a unit fraction, and compute such quotients.',
  1),
('CCSS.Math.Content.5.NF.B.7a',
  'Interpret division of a unit fraction by a non-zero whole number, and compute such quotients.',
  1),
('CCSS.Math.Content.5.NF.B.7',
  'Apply and extend previous understandings of division to divide unit fractions by whole numbers and whole numbers by unit fractions.',
  1),
('CCSS.Math.Content.5.NF.B.6',
  'Solve real world problems involving multiplication of fractions and mixed numbers, e.g., by using visual fraction models or equations to represent the problem.',
  1),
('CCSS.Math.Content.5.NF.B.5b',
  'Explaining why multiplying a given number by a fraction greater than 1 results in a product greater than the given number (recognizing multiplication by whole numbers greater than 1 as a familiar case); explaining why multiplying a given number by a fraction less than 1 results in a product smaller than the given number; and relating the principle of fraction equivalence a/b = (n×a)/(n×b) to the effect of multiplying a/b by 1.',
  1),
('CCSS.Math.Content.5.NF.B.5a',
  'Comparing the size of a product to the size of one factor on the basis of the size of the other factor, without performing the indicated multiplication.',
  1),
('CCSS.Math.Content.5.NF.B.5',
  'Interpret multiplication as scaling (resizing), by:',
  1),
('CCSS.Math.Content.5.NF.B.4b',
  'Find the area of a rectangle with fractional side lengths by tiling it with unit squares of the appropriate unit fraction side lengths, and show that the area is the same as would be found by multiplying the side lengths. Multiply fractional side lengths to find areas of rectangles, and represent fraction products as rectangular areas.',
  1),
('CCSS.Math.Content.5.NF.B.4a',
  'Interpret the product (a/b) × q as a parts of a partition of q into b equal parts; equivalently, as the result of a sequence of operations a × q ÷ b.',
  1),
('CCSS.Math.Content.5.NF.B.4',
  'Apply and extend previous understandings of multiplication to multiply a fraction or whole number by a fraction.',
  1),
('CCSS.Math.Content.5.NF.B.3',
  'Interpret a fraction as division of the numerator by the denominator (a/b = a ÷ b). Solve word problems involving division of whole numbers leading to answers in the form of fractions or mixed numbers, e.g., by using visual fraction models or equations to represent the problem.',
  1),
('CCSS.Math.Content.5.NF.B',
  'Apply and extend previous understandings of multiplication and division to multiply and divide fractions.',
  1),
('CCSS.Math.Content.5.NF.A.2',
  'Solve word problems involving addition and subtraction of fractions referring to the same whole, including cases of unlike denominators, e.g., by using visual fraction models or equations to represent the problem. Use benchmark fractions and number sense of fractions to estimate mentally and assess the reasonableness of answers.',
  1),
('CCSS.Math.Content.5.NF.A.1',
  'Add and subtract fractions with unlike denominators (including mixed numbers) by replacing given fractions with equivalent fractions in such a way as to produce an equivalent sum or difference of fractions with like denominators.',
  1),
('CCSS.Math.Content.5.NF.A',
  'Use equivalent fractions as a strategy to add and subtract fractions.',
  1),
('CCSS.Math.Content.5.G.B.4',
  'Classify two-dimensional figures in a hierarchy based on properties.',
  1),
('CCSS.Math.Content.5.G.B.3',
  'Understand that attributes belonging to a category of two-dimensional figures also belong to all subcategories of that category.',
  1),
('CCSS.Math.Content.5.G.B',
  'Classify two-dimensional figures into categories based on their properties.',
  1),
('CCSS.Math.Content.5.G.A.2',
  'Represent real world and mathematical problems by graphing points in the first quadrant of the coordinate plane, and interpret coordinate values of points in the context of the situation.',
  1),
('CCSS.Math.Content.5.G.A.1',
  'Use a pair of perpendicular number lines, called axes, to define a coordinate system, with the intersection of the lines (the origin) arranged to coincide with the 0 on each line and a given point in the plane located by using an ordered pair of numbers, called its coordinates. Understand that the first number indicates how far to travel from the origin in the direction of one axis, and the second number indicates how far to travel in the direction of the second axis, with the convention that the names of the two axes and the coordinates correspond (e.g., x-axis and x-coordinate, y-axis and y-coordinate).',
  1),
('CCSS.Math.Content.5.G.A',
  'Graph points on the coordinate plane to solve real-world and mathematical problems.',
  1),
('CCSS.Math.Content.5.MD.C.5c',
  'Recognize volume as additive. Find volumes of solid figures composed of two non-overlapping right rectangular prisms by adding the volumes of the non-overlapping parts, applying this technique to solve real world problems.',
  1),
('CCSS.Math.Content.5.MD.C.5b',
  'Apply the formulas V = l × w × h and V = b × h for rectangular prisms to find volumes of right rectangular prisms with whole-number edge lengths in the context of solving real world and mathematical problems.',
  1),
('CCSS.Math.Content.5.MD.C.5a',
  'Find the volume of a right rectangular prism with whole-number side lengths by packing it with unit cubes, and show that the volume is the same as would be found by multiplying the edge lengths, equivalently by multiplying the height by the area of the base. Represent threefold whole-number products as volumes, e.g., to represent the associative property of multiplication.',
  1),
('CCSS.Math.Content.5.MD.C.5',
  'Relate volume to the operations of multiplication and addition and solve real world and mathematical problems involving volume.',
  1),
('CCSS.Math.Content.5.MD.C.4',
  'Measure volumes by counting unit cubes, using cubic cm, cubic in, cubic ft, and improvised units.',
  1),
('CCSS.Math.Content.5.MD.C.3b',
  'A solid figure which can be packed without gaps or overlaps using n unit cubes is said to have a volume of n cubic units.',
  1),
('CCSS.Math.Content.5.MD.C.3a',
  'A cube with side length 1 unit, called a "unit cube," is said to have "one cubic unit" of volume, and can be used to measure volume.',
  1),
('CCSS.Math.Content.5.MD.C.3',
  'Recognize volume as an attribute of solid figures and understand concepts of volume measurement.',
  1),
('CCSS.Math.Content.5.MD.C',
  'Geometric measurement: understand concepts of volume and relate volume to multiplication and to addition.',
  1),
('CCSS.Math.Content.5.MD.B.2',
  'Make a line plot to display a data set of measurements in fractions of a unit (1/2, 1/4, 1/8). Use operations on fractions for this grade to solve problems involving information presented in line plots.',
  1),
('CCSS.Math.Content.5.MD.B',
  'Represent and interpret data.',
  1),
('CCSS.Math.Content.5.MD.A.1',
  'Convert among different-sized standard measurement units within a given measurement system (e.g., convert 5 cm to 0.05 m), and use these conversions in solving multi-step, real world problems.',
  1),
('CCSS.Math.Content.5.MD.A',
  'Convert like measurement units within a given measurement system.',
  1),
('CCSS.Math.Content.5.NBT.B.7',
  'Add, subtract, multiply, and divide decimals to hundredths, using concrete models or drawings and strategies based on place value, properties of operations, and/or the relationship between addition and subtraction; relate the strategy to a written method and explain the reasoning used.',
  1),
('CCSS.Math.Content.5.NBT.B.6',
  'Find whole-number quotients of whole numbers with up to four-digit dividends and two-digit divisors, using strategies based on place value, the properties of operations, and/or the relationship between multiplication and division. Illustrate and explain the calculation by using equations, rectangular arrays, and/or area models.',
  1),
('CCSS.Math.Content.5.NBT.B.5',
  'Fluently multiply multi-digit whole numbers using the standard algorithm.',
  1),
('CCSS.Math.Content.5.NBT.B',
  'Perform operations with multi-digit whole numbers and with decimals to hundredths.',
  1),
('CCSS.Math.Content.5.NBT.A.4',
  'Use place value understanding to round decimals to any place.',
  1),
('CCSS.Math.Content.5.NBT.A.3b',
  'Compare two decimals to thousandths based on meanings of the digits in each place, using >, =, and < symbols to record the results of comparisons.',
  1),
('CCSS.Math.Content.5.NBT.A.3a',
  'Read and write decimals to thousandths using base-ten numerals, number names, and expanded form, e.g., 347.392 = 3 × 100 + 4 × 10 + 7 × 1 + 3 × (1/10) + 9 × (1/100) + 2 × (1/1000).',
  1),
('CCSS.Math.Content.5.NBT.A.3',
  'Read, write, and compare decimals to thousandths.',
  1),
('CCSS.Math.Content.5.NBT.A.2',
  'Explain patterns in the number of zeros of the product when multiplying a number by powers of 10, and explain patterns in the placement of the decimal point when a decimal is multiplied or divided by a power of 10. Use whole-number exponents to denote powers of 10.',
  1),
('CCSS.Math.Content.5.NBT.A.1',
  'Recognize that in a multi-digit number, a digit in one place represents 10 times as much as it represents in the place to its right and 1/10 of what it represents in the place to its left.',
  1),
('CCSS.Math.Content.5.NBT.A',
  'Understand the place value system.',
  1),
('CCSS.Math.Content.5.OA.B.3',
  'Generate two numerical patterns using two given rules. Identify apparent relationships between corresponding terms. Form ordered pairs consisting of corresponding terms from the two patterns, and graph the ordered pairs on a coordinate plane.',
  1),
('CCSS.Math.Content.5.OA.B',
  'Analyze patterns and relationships.',
  1),
('CCSS.Math.Content.5.OA.A.2',
  'Write simple expressions that record calculations with numbers, and interpret numerical expressions without evaluating them.',
  1),
('CCSS.Math.Content.5.OA.A.1',
  'Use parentheses, brackets, or braces in numerical expressions, and evaluate expressions with these symbols.',
  1),
('CCSS.Math.Content.5.OA.A',
  'Write and interpret numerical expressions.',
  1),
('CCSS.Math.Practice.MP8',
  'Look for and express regularity in repeated reasoning.',
  1),
('CCSS.Math.Practice.MP7',
  'Look for and make use of structure.',
  1),
('CCSS.Math.Practice.MP6',
  'Attend to precision.',
  1),
('CCSS.Math.Practice.MP5',
  'Use appropriate tools strategically.',
  1),
('CCSS.Math.Practice.MP4',
  'Model with mathematics.',
  1),
('CCSS.Math.Practice.MP3',
  'Construct viable arguments and critique the reasoning of others.',
  1),
('CCSS.Math.Practice.MP2',
  'Reason abstractly and quantitatively.',
  1),
('CCSS.Math.Practice.MP1',
  'Make sense of problems and persevere in solving them.',
  1),
('5-PS3-1',
  'Use models to describe that energy in animals'' food (used for body repair, growth, motion, and to maintain body warmth) was once energy from the sun.',
  3),
('5-PS3',
  'Energy',
  3),
('5-PS2-1',
  'Support an argument that the gravitational force exerted by Earth on objects is directed down.',
  3),
('5-PS2',
  'Motion and Stability: Forces and Interactions',
  3),
('5-PS1-4',
  'Conduct an investigation to determine whether the mixing of two or more substances results in new substances.',
  3),
('5-PS1-3',
  'Make observations and measurements to identify materials based on their properties.',
  3),
('5-PS1-2',
  'Measure and graph quantities to provide evidence that regardless of the type of change that occurs when heating, cooling, or mixing substances, the total weight of matter is conserved.',
  3),
('5-PS1-1',
  'Develop a model to describe that matter is made of particles too small to be seen.',
  3),
('5-PS1',
  'Matter and Its Interactions',
  3),
('5-ESS3-1',
  'Obtain and combine information about ways individual communities use science ideas to protect the Earth''s resources and environment.',
  3),
('5-ESS3',
  'Earth and Human Activity',
  3),
('5-ESS2-2',
  'Describe and graph the amounts and percentages of water and fresh water in various reservoirs to provide evidence about the distribution of water on Earth.',
  3),
('5-ESS2-1',
  'Develop a model using an example to describe ways the geosphere, biosphere, hydrosphere, and/or atmosphere interact.',
  3),
('5-ESS2',
  'Earth''s Systems',
  3),
('5-ESS1-2',
  'Represent data in graphical displays to reveal patterns of daily changes in length and direction of shadows, day and night, and the seasonal appearance of some stars in the night sky.',
  3),
('5-ESS1-1',
  'Support an argument that differences in the apparent brightness of the sun compared to other stars is due to their relative distances from Earth.',
  3),
('5-ESS1',
  'Earth''s Place in the Universe',
  3),
('5-LS2-1',
  'Develop a model to describe the movement of matter among plants, animals, decomposers, and the environment.',
  3),
('5-LS2',
  'Ecosystems: Interactions, Energy, and Dynamics',
  3),
('5-LS1-1',
  'Support an argument that plants get the materials they need for growth chiefly from air and water.',
  3),
('5-LS1',
  'From Molecules to Organisms: Structures and Processes',
  3),
('3-5-ETS1-3',
  'Plan and carry out fair tests in which variables are controlled and failure points are considered to identify aspects of a model or prototype that can be improved.',
  3),
('3-5-ETS1-2',
  'Generate and compare multiple possible solutions to a problem based on how well each is likely to meet the criteria and constraints of the problem.',
  3),
('3-5-ETS1-1',
  'Define a simple design problem reflecting a need or a want that includes specified criteria for success and constraints on materials, time, or cost.',
  3),
('3-5-ETS1',
  'Engineering Design',
  3)

